stages:
  preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/Online Retail.xlsx
    outs:
      - data/prepared/train.csv

  training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/prepared/train.csv
    outs:
      - models/model.pkl

  evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/prepared/train.csv
    metrics:
      - metrics.json
    plots:
      - plots/prediction.png